CREATE DATABASE adote_pet_db; -- CRIA UMA NOVA BASE DE DADOS

-- CRIA UMA TABELA DE USUARIO
CREATE TABLE usuario (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  celular VARCHAR(11) NOT NULL,
  img VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  CONSTRAINT pk_usuario PRIMARY KEY(id)
);

-- CRIA UMA TABELA DE POSTAGEM
CREATE TABLE postagem (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  sexo VARCHAR(255) NOT NULL,
  idade VARCHAR(255) NOT NULL,
  porte VARCHAR(255) NOT NULL,
  endereco VARCHAR(255) NOT NULL,
  data_postagem TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  historia VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  disponibilidade INT(1) NOT NULL,
  id_usuario INT(11) NOT NULL,
  id_categoria INT(11) NOT NULL,
  CONSTRAINT pk_postagem PRIMARY KEY(id),
  CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id),
  CONSTRAINT fk_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

-- CRIA UMA TABELA DE CATEGORIA
CREATE TABLE categoria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  CONSTRAINT pk_categoria PRIMARY KEY(id)
);